kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: suyeshsingh@outlook.com
        send_resolved: true
        from: from-email@email.com
        smarthost: smtp.eample.com:25
        require_tls: false
        auth_username: mail_id@gmail.com
        auth_identity: mail_id@gmail.com
        auth_password: <Enter password here>
