kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
   receivers:
    - name: alert-emailer
      email_configs:
      - to: demo@devopscube.com
        from: 'email_id@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'email_id@gmail.com'
        auth_identity: 'email_id@gmail.com'
        auth_password: 'password'
